image: ghcr.io/frosit/{arch}-base-ubuntu
build_from:
  aarch64: "arm64v8/ubuntu:"
  armv7: "arm32v7/ubuntu:"
  amd64: "ubuntu:"
cosign:
  identity: https://github.com/frosit/docker-base/.*
args:
  S6_OVERLAY_VERSION: 3.1.6.2
labels:
  io.hass.base.name: ubuntu
  org.opencontainers.image.source: https://github.com/frosit/docker-base
